name: Running on another action

on:
  workflow_run:
    workflows:
      - "Trigger the ViewBuilder"
    types:
      - completed

jobs:
  notify:
    name: second-job
    runs-on: ubuntu-latest
    steps:
      - name: echo-second
        shell: bash
        run:  echo "Running on complete!"

